import { GameState } from './status';

export const mockGameState: GameState = {
  player: {
    name: "Eldric the Wanderer",
    class: "Wizard",
    status: {
      health: 85,
      maxHealth: 100,
      mana: 45,
      maxMana: 80,
      stamina: 60,
      maxStamina: 100,
      level: 7,
      experience: 2150,
      experienceToNext: 3000,
    },
    statusTags: [
      {
        id: "buff-1",
        name: "Arcane Focus",
        type: "buff",
        description: "Increases magical damage by 25%. Your spells crackle with enhanced power.",
        duration: 300,
        remainingTime: 245,
        icon: "✨",
        stackable: false,
      },
      {
        id: "debuff-1",
        name: "Cursed",
        type: "debuff",
        description: "Reduces all healing received by 50%. Dark magic courses through your veins.",
        duration: 600,
        remainingTime: 480,
        icon: "💀",
        stackable: false,
      },
      {
        id: "status-1",
        name: "Blessed",
        type: "status",
        description: "Protected by divine grace. Immune to fear and charm effects.",
        duration: undefined, // Permanent
        icon: "🛡️",
        stackable: false,
      },
      {
        id: "buff-2",
        name: "Potion of Strength",
        type: "buff",
        description: "Increases physical damage and carrying capacity.",
        duration: 180,
        remainingTime: 120,
        icon: "💪",
        stackable: true,
        stackCount: 2,
      },
      {
        id: "neutral-1",
        name: "Well Fed",
        type: "neutral",
        description: "Recent meal provides sustained energy. Slower hunger decay.",
        duration: 1200,
        remainingTime: 850,
        icon: "🍖",
        stackable: false,
      },
    ],
    inventory: [
      {
        id: "weapon-1",
        name: "Staff of Elemental Mastery",
        description: "A powerful staff that channels the raw forces of fire, ice, and lightning. Carved from ancient dragonbone.",
        type: "weapon",
        quantity: 1,
        equipped: true,
        rarity: "epic",
        icon: "🔮",
        weight: 2.5,
        value: 1500,
      },
      {
        id: "armor-1",
        name: "Robes of the Arcane Scholar",
        description: "Comfortable robes woven with magical threads. Enhances mana regeneration.",
        type: "armor",
        quantity: 1,
        equipped: true,
        rarity: "rare",
        icon: "👘",
        weight: 1.0,
        value: 750,
      },
      {
        id: "consumable-1",
        name: "Health Potion",
        description: "A glowing red potion that restores 50 health when consumed.",
        type: "consumable",
        quantity: 5,
        equipped: false,
        rarity: "common",
        icon: "🧪",
        weight: 0.2,
        value: 25,
      },
      {
        id: "consumable-2",
        name: "Mana Potion",
        description: "A shimmering blue potion that restores 40 mana when consumed.",
        type: "consumable",
        quantity: 3,
        equipped: false,
        rarity: "common",
        icon: "🔵",
        weight: 0.2,
        value: 30,
      },
      {
        id: "tool-1",
        name: "Enchanted Lockpicks",
        description: "Masterwork lockpicks infused with subtle magic. Never break and improve success rate.",
        type: "tool",
        quantity: 1,
        equipped: false,
        rarity: "uncommon",
        icon: "🔓",
        weight: 0.1,
        value: 200,
      },
      {
        id: "misc-1",
        name: "Ancient Tome",
        description: "A weathered book containing forgotten spells. Written in an archaic dialect.",
        type: "misc",
        quantity: 1,
        equipped: false,
        rarity: "legendary",
        icon: "📚",
        weight: 1.5,
        value: 2000,
      },
      {
        id: "misc-2",
        name: "Dragon Scale",
        description: "A shimmering scale from an ancient red dragon. Radiates latent magical energy.",
        type: "misc",
        quantity: 2,
        equipped: false,
        rarity: "rare",
        icon: "🐉",
        weight: 0.5,
        value: 500,
      },
    ],
  },
  scene: {
    id: "scene-1",
    name: "The Whispering Woods",
    description: "Dense forest where ancient magic still lingers. Twisted trees reach toward a cloudy sky, their branches forming natural archways. Strange lights flicker between the trunks.",
    location: "Northern Elderwood",
    weatherCondition: "Misty",
    timeOfDay: "Dusk",
    ambientEffects: ["Mystical whispers", "Floating orbs of light", "Rustling leaves"],
  },
  lastUpdated: new Date(),
};

export const mockGameStateMinimal: GameState = {
  player: {
    name: "Aria",
    class: "Rogue",
    status: {
      health: 100,
      maxHealth: 100,
      level: 1,
      experience: 0,
      experienceToNext: 1000,
    },
    statusTags: [],
    inventory: [],
  },
  scene: {
    id: "scene-start",
    name: "Starting Village",
    description: "A peaceful village where your adventure begins.",
    location: "Greenfields",
  },
  lastUpdated: new Date(),
};